apiVersion: v1
kind: ConfigMap
metadata:
  {{- $adminServiceFullName := include "apollo.adminService.fullName" . }}
  name: {{ $adminServiceFullName }}
  labels:
    app.kubernetes.io/component: adminService
    {{- include "apollo.service.labels" . | nindent 4 }}
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{include "apollo.configdb.serviceName" .}}:{{include "apollo.configdb.servicePort" .}}/{{ .Values.db.configdb.dbName }}{{ if .Values.db.configdb.connectionStringProperties }}?{{ .Values.db.configdb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "configdb.userName is required!" .Values.db.configdb.userName  }}
    spring.datasource.password = {{ required "configdb.password is required!" .Values.db.configdb.password  }}
    {{- if .Values.adminService.config.contextPath }}
    server.servlet.context-path = {{ .Values.adminService.config.contextPath }}
    {{- end }}