#
# Copyright 2021 Apollo Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apollo.adminService.serviceName" . }}
  labels:
    app.kubernetes.io/component: adminService
    {{- include "apollo.service.labels" . | nindent 4 }}
    {{- if .Values.adminService.service.extraLabels }}
    {{- range $key, $value := .Values.adminService.service.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- if .Values.adminService.service.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.adminService.service.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
{{- with .Values.adminService.service }}
  type: {{ .type }}
  {{- if and (eq .type "LoadBalancer") .externalTrafficPolicy }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .type "LoadBalancer") .loadBalancerIP }}
  loadBalancerIP: {{ .externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .port }}
      targetPort: http
      {{- if and (or (eq .type "NodePort") (eq .type "LoadBalancer")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  selector:
    app: {{ include "apollo.adminService.fullName" $ }}
{{- end }}