apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgcat.fullname" . }}
  labels:
    {{- include "pgcat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgcat
      protocol: TCP
      name: pgcat
    {{- if and .Values.configuration.general.enable_prometheus_exporter .Values.configuration.general.prometheus_exporter_port }}
    - name: metrics
      port: {{ .Values.configuration.general.prometheus_exporter_port }}
      targetPort: {{ .Values.configuration.general.prometheus_exporter_port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "pgcat.selectorLabels" . | nindent 4 }}
