{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "xxl-job-admin.fullname" . }}
spec:
  hosts:
  {{- include "xxl-job-admin.virtualservice.hosts" . | indent 4 }}
  gateways:
  {{- include "xxl-job-admin.virtualservice.gateways" . | indent 4 }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "xxl-job-admin.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end}}