# Default values for xxl-job-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: xuxueli/xxl-job-admin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.3.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## configure the database detail
database:
#  url: "jdbc:mysql://x.x.x.x:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
  db_address: x.x.x.x
  db_port: 3306
  user: xxl-job
  password: password_string
  db_name: xxl_job
  serverTimezone: UTC

## overwrite the default value of properties in application.yaml
properties:
  management:
    health:
      mail:
        enabled: false
    server:
      servlet:
        context-path: /actuator
  mybatis:
    mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
  server:
    port: 8080
    servlet:
      context-path: /xxl-job-admin
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 10000
        idle-timeout: 30000
        max-lifetime: 900000
        maximum-pool-size: 30
        minimum-idle: 10
        pool-name: HikariCP
        validation-timeout: 1000
      password: ${mysql.password}
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${mysql.url}/${mysql.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
      username: ${mysql.user}
    freemarker:
      charset: UTF-8
      request-context-attribute: request
      settings:
        number_format: 0.##########
      suffix: .ftl
      templateLoaderPath: classpath:/templates/
    mail:
      from:
      host:
      password:
      port:
      properties:
        mail:
          smtp:
            auth: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
            starttls:
              enable: true
              required: true
      username:
    mvc:
      servlet:
        load-on-startup: 0
      static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
  xxl:
    job:
      accessToken: "default_token_dev"
      i18n: zh_CN
      logretentiondays: 10
      triggerpool:
        fast:
          max: 200
        slow:
          max: 100

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

# default label name includes:
## helm.sh/chart:
## app.kubernetes.io/name:
## app.kubernetes.io/instance:
## app.kubernetes.io/version:
## app.kubernetes.io/managed-by:
## app:
## version:
podLabels: {}

podEnviron: {}
  # foo: bar
  # key1: value1

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: xxl-job.example.com
      paths:
        - path: /xxl-job-admin
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

virtualservice:
  # Istio VirtualService
  enabled: false
  hosts:
    - xxl-job.example.com
  gateways:
    - default/default-gateway
    - middleware-gateway


resources:
  #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1500m
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}