apiVersion: v1
kind: Service
metadata:
  name: {{ include "canal-server.fullname" . }}
  labels:
    {{- include "canal-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.canal }}
      targetPort: tcp-canal
      protocol: TCP
      name: tcp-canal
    - port: {{ .Values.service.ports.admin }}
      targetPort: tcp-admin
      protocol: TCP
      name: tcp-admin
    - port: {{ .Values.service.ports.metrics }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "canal-server.selectorLabels" . | nindent 4 }}
