{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "fleet-management.resourceName" (dict "suffix" "api" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            {{- if $.Values.gateway.enabled }}
            name: {{ include "fleet-management.resourceName" (dict "suffix" "gateway" "context" $) }}
            port:
              name: proxy
            {{- else }}
            name: {{ include "fleet-management.resourceName" (dict "suffix" "api" "context" $) }}
            port:
              name: connect-rpc
            {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
