{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "fleet-management.resourceName" (dict "suffix" "api" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: connect-rpc
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: connect-rpc
  selector:
    {{- include "fleet-management.selectorLabels" . | nindent 4 }}
{{- end }}
