annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.8.1
dependencies:
  - name: common
    repository: https://dellnoantechnp.github.io/helm-chart-xxl-job-admin/
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: zookeeper.enabled
    name: zookeeper
    repository: https://dellnoantechnp.github.io/helm-chart-xxl-job-admin/
    version: 7.x.x
description: "[OpenSource by Bitnami] Apache Kafka is a distributed streaming platform."
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kafka
icon: https://raw.githubusercontent.com/dellnoantechnp/helm-chart-xxl-job-admin/main/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
  - kafka
  - zookeeper
  - streaming
  - producer
  - consumer
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: kafka
sources:
  - https://github.com/bitnami/bitnami-docker-kafka
  - https://kafka.apache.org/
version: 14.9.3
