apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xxl-job-admin.fullname" . }}-creds
  labels:
    {{- include "xxl-job-admin.labels" . | nindent 4 }}
type: Opaque
data:
  mysql.url: {{ required "database.url is required" .Values.database.url | b64enc | quote }}
  {{- with .Values.database.user }}
  mysql.user: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.database.password }}
  mysql.password: {{ . | b64enc | quote }}
  {{- end }}
  mysql.database: {{ required "database.db is required" .Values.database.db | b64enc | quote }}