apiVersion: v1
kind: ConfigMap
metadata:
  {{- $configServiceFullName := include "apollo.configService.fullName" . }}
  name: {{ $configServiceFullName }}
  labels:
    app.kubernetes.io/component: configService
    {{- include "apollo.service.labels" . | nindent 4 }}
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{include "apollo.configdb.serviceName" .}}:{{include "apollo.configdb.servicePort" .}}/{{ .Values.db.configdb.dbName }}{{ if .Values.db.configdb.connectionStringProperties }}?{{ .Values.db.configdb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "configdb.userName is required!" .Values.db.configdb.userName | quote }}
    spring.datasource.password = {{ required "configdb.password is required!" .Values.db.configdb.password | quote }}
    apollo.config-service.url = {{ include "apollo.configService.serviceUrl" .}}
    apollo.admin-service.url = {{ include "apollo.adminService.serviceUrl" .}}
    {{- if .Values.configService.config.contextPath }}
    server.servlet.context-path = {{ .Values.configService.config.contextPath }}
    {{- end }}