#
# Copyright 2021 Apollo Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- $configServiceFullName := include "apollo.configService.fullName" . }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $configServiceFullName }}
  labels:
    {{- include "apollo.service.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/config-service/configmap-configservice.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.configService.replicaCount }}
  selector:
    matchLabels:
      app: {{ $configServiceFullName }}
  {{- with .Values.configService.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $configServiceFullName }}
      {{- with .Values.configService.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.configService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: volume-configmap-{{ $configServiceFullName }}
          configMap:
            name: {{ $configServiceFullName }}
            items:
              - key: application-github.properties
                path: application-github.properties
              {{- if .Values.db.configdb.autoInitDatabase.enabled }}
              - key: init-database.sql
                path: init-database.sql
              {{- end }}
            defaultMode: 420
      {{- if .Values.db.configdb.autoInitDatabase.enabled }}
      initContainers:
        - name: init-database
          image: "{{ .Values.db.configdb.autoInitDatabase.initContainer.registry }}/{{ .Values.db.configdb.autoInitDatabase.initContainer.repository }}:{{ .Values.db.configdb.autoInitDatabase.initContainer.tag }}"
          env:
            - name: MYSQL_HOST
              value: {{ .Values.db.configdb.host }}
          command:
            - bash
            - "-ec"
          args:
            - |
              echo "INFO: Start to init database."
              cat > /tmp/.my.cnf << EOF
              [client]
              host={{ .Values.db.configdb.host }}
              user={{ .Values.db.configdb.userName | quote }}
              password={{ .Values.db.configdb.password | quote }}
              database={{ .Values.db.configdb.dbName }}
              EOF
              echo "INFO: Checking the database, if it's exist ..."
              if mysql --defaults-file=/tmp/.my.cnf -E --connect-timeout=30 -w -e 'SHOW TABLES FROM {{ .Values.db.configdb.dbName }}' | grep -q : ; then
                echo "INFO: {{ .Values.db.configdb.dbName }} was exists. skipping to initial SQL table."
              else
              #if [[ $? -eq 1 ]]; then
                echo "INFO: {{ .Values.db.configdb.dbName }} is not exists. creating and init SQL file ..."
                echo "INFO: CREATE DATABASE"
                mysql --defaults-file=/tmp/.my.cnf -E --connect-timeout=30 -w -e 'CREATE DATABASE "{{ .Values.db.configdb.dbName }}" DEFAULT CHARSET utf8mb4'
                echo "INFO: CREATE TABLES"
                mysql --defaults-file=/tmp/.my.cnf -E --connect-timeout=30 -w {{ .Values.db.configdb.dbName }} < /docker-entrypoint-initdb.d/init-database.sql
              fi
              echo "INFO: starting app container ..."
          volumeMounts:
            - name: volume-configmap-{{ $configServiceFullName }}
              mountPath: /tmp/application-github.properties
              subPath: application-github.properties
            - name: volume-configmap-{{ $configServiceFullName }}
              mountPath: /docker-entrypoint-initdb.d/init-database.sql
              subPath: init-database.sql
      {{- end }}
      containers:
        - name: {{ .Values.configService.name }}
          image: "{{ .Values.configService.image.repository }}:{{ .Values.configService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.configService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.configService.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.configService.config.profiles | quote }}
          {{- range $key, $value := .Values.configService.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: volume-configmap-{{ $configServiceFullName }}
              mountPath: /apollo-configservice/config/application-github.properties
              subPath: application-github.properties
          livenessProbe:
            tcpSocket:
              port: {{ .Values.configService.containerPort }}
            initialDelaySeconds: {{ .Values.configService.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.configService.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.configService.config.contextPath }}/health
              port: {{ .Values.configService.containerPort }}
            initialDelaySeconds: {{ .Values.configService.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.configService.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.configService.resources | nindent 12 }}
    {{- with .Values.configService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.configService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.configService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
