apiVersion: v2
appVersion: 1.2.0
description: A Helm chart for PgCat a PostgreSQL pooler and proxy (like PgBouncer)
  with support for sharding, load balancing, failover and mirroring.
maintainers:
- email: dellnoantechnp@gmail.com
  name: dellnoantechnp
- email: team@postgresml.org
  name: PostgresML
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
name: pgcat
version: 0.3.0
kubeVersion: ">=1.26.0"
