{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
    {{- include "fleet-management.selectorLabels" . | nindent 4 }}
  name: {{ include "fleet-management.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "fleet-management.selectorLabels" . | nindent 4 }}
{{- end }}
