{{- if .Values.portal.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  {{- $portalFullName := include "apollo.portal.fullName" . }}
  name: {{ $portalFullName }}
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://{{include "apollo.portaldb.serviceName" .}}:{{include "apollo.portaldb.servicePort" .}}/{{ .Values.db.portaldb.dbName }}{{ if .Values.db.portaldb.connectionStringProperties }}?{{ .Values.db.portaldb.connectionStringProperties }}{{ end }}
    spring.datasource.username = {{ required "portaldb.userName is required!" .Values.db.portaldb.userName }}
    spring.datasource.password = {{ required "portaldb.password is required!" .Values.db.portaldb.password }}
    {{- if .Values.portal.config.envs }}
    apollo.portal.envs = {{ .Values.portal.config.envs }}
    {{- end }}
    {{- if .Values.portal.config.contextPath }}
    server.servlet.context-path = {{ .Values.portal.config.contextPath }}
    {{- end }}
  apollo-env.properties: |
    {{- range $env, $address := .Values.portal.config.metaServers }}
    {{ $env }}.meta = {{ $address }}
    {{- end }}
    {{- if not .Values.portal.config.metaServers }}
    {{ .Values.portal.config.envs }}: {{ include "apollo.configService.serviceUrl" . }}{{ .Values.configService.config.contextPath }}
    {{- end }}
    {{- range $fileName, $content := .Values.portal.config.files }}
    {{ $fileName | nindent 4 }}: |
    {{ $content | nindent 4 }}
    {{- end }}
  {{- if .Values.db.portaldb.autoInitDatabase.enabled }}
  init-database.sql: |
    {{- .Files.Get "init-db/apolloportaldb.sql" | nindent 4 }}
  {{- end }}
{{- end }}