#
# Copyright 2021 Apollo Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $portalFullName := include "apollo.portal.fullName" . }}
  name: {{ $portalFullName }}
  labels:
    {{- include "apollo.portal.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/portal/configmap-portal.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      app: {{ $portalFullName }}
  {{- with .Values.portal.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ $portalFullName }}
      {{- with .Values.portal.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.portal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: configmap-{{ $portalFullName }}
          configMap:
            name: {{ $portalFullName }}
            items:
              - key: application-github.properties
                path: application-github.properties
              - key: apollo-env.properties
                path: apollo-env.properties
            {{- range $fileName, $content := .Values.portal.config.files }}
              - key: {{ $fileName }}
                path: {{ $fileName }}
            {{- end }}
            defaultMode: 420
      containers:
        - name: {{ .Values.portal.name }}
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.portal.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.portal.config.profiles | quote }}
          {{- range $key, $value := .Values.portal.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name: configmap-{{ $portalFullName }}
              mountPath: /apollo-portal/config/application-github.properties
              subPath: application-github.properties
            - name: configmap-{{ $portalFullName }}
              mountPath: /apollo-portal/config/apollo-env.properties
              subPath: apollo-env.properties
          {{- range $fileName, $content := .Values.portal.config.files }}
            - name: configmap-{{ $portalFullName }}
              mountPath: /apollo-portal/config/{{ $fileName }}
              subPath: {{ $fileName }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.portal.containerPort }}
            initialDelaySeconds: {{ .Values.portal.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.portal.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.portal.config.contextPath }}/health
              port: {{ .Values.portal.containerPort }}
            initialDelaySeconds: {{ .Values.portal.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.portal.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.portal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
