{{- if and .Values.portal.serviceMonitor.enabled .Values.portal.prometheusRule.enabled .Values.portal.prometheusRule.rules }}
{{- with .Values.portal }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "apollo.portal.fullName" $ }}
  {{- if .prometheusRule.namespace }}
  namespace: {{ .prometheusRule.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: apollo-portal
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .prometheusRule.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .prometheusRule.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "apollo.portal.fullName" $ }}
      rules: {{- toYaml .prometheusRule.rules | nindent 8 }}
{{- end }}
{{- end }}

