{{- if .Values.portal.enabled }}
{{- if .Values.portal.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "apollo.portal.fullName" . }}
  {{- if .Values.portal.serviceMonitor.namespace }}
  namespace: {{ .Values.portal.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: apollo-portal
    {{- if .Values.portal.serviceMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.portal.serviceMonitor.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.portal.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.portal.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      {{- if .Values.portal.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.portal.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: apollo-portal
  endpoints:
    - port: {{ .Values.portal.service.port }}
      path: {{ .Values.portal.serviceMonitor.metricPath | default "/metrics" }}
      {{- if .Values.portal.serviceMonitor.interval }}
      interval: {{ .Values.portal.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.portal.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.portal.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.portal.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.portal.serviceMonitor.relabelings "context" $) | nindent 6 }}
      {{- end }}
      {{- if .Values.portal.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.portal.serviceMonitor.metricRelabelings "context" $) | nindent 6 }}
      {{- end }}
      {{- if .Values.portal.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.portal.serviceMonitor.honorLabels }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ template "apollo.release.namespace" . }}
{{- end }}
{{- end }}