apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
  name: {{ include "fleet-management.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
