apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fleet-management.resourceName" (dict "suffix" "manager-role" "context" $) }}
rules:
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - collectorgroupbindings
  - collectorgroups
  - pipelineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - collectorgroupbindings/finalizers
  - collectorgroups/finalizers
  - pipelineconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - collectorgroupbindings/status
  - collectorgroups/status
  - pipelineconfigs/status
  verbs:
  - get
  - patch
  - update
