{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
  name: {{ include "fleet-management.resourceName" (dict "suffix" "pipelineconfig-editor-role" "context" $) }}
rules:
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - pipelineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.pkarakal.com
  resources:
  - pipelineconfigs/status
  verbs:
  - get
{{- end }}
