apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kadalu-operator
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.operator.service.annotations }}
  annotations:
    {{- if .Values.operator.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.operator.service.type }}
  {{- if and .Values.operator.service.clusterIP (eq .Values.operator.service.type "ClusterIP") }}
  clusterIP: {{ .Values.operator.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.operator.service.type "LoadBalancer") (eq .Values.operator.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.operator.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.operator.service.type "LoadBalancer") (not (empty .Values.operator.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.operator.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.operator.service.type "LoadBalancer") (not (empty .Values.operator.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.operator.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.operator.service.sessionAffinity }}
  sessionAffinity: {{ .Values.operator.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.operator.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http-api
      port: {{ .Values.operator.service.port }}
      targetPort: {{ .Values.operator.containerPort.name }}
      {{- if and (or (eq .Values.operator.service.type "NodePort") (eq .Values.operator.service.type "LoadBalancer")) (not (empty .Values.operator.service.nodePorts.client)) }}
      nodePort: {{ .Values.operator.service.nodePorts.client }}
      {{- else if eq .Values.operator.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: kadalu-operator
