{{- if and .Values.gateway.enabled .Values.gateway.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "fleet-management.labels" . | nindent 4 }}
  name: {{ include "fleet-management.resourceName" (dict "suffix" "gateway" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "fleet-management.gatewaySelectorLabels" . | nindent 6 }}
  {{- if .Values.gateway.pdb.minAvailable }}
  minAvailable: {{ .Values.gateway.pdb.minAvailable }}
  {{- else if .Values.gateway.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.gateway.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
{{- end }}
